#include "handleWebServer.h"

void homePage(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>molen</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Teller van de sensor: \r\n";
  result += "<span id='rawCounter'>-</span>\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<!-- ratio is 1:\r\n";
  result += "<span id='ratio'>-</span>\r\n";
  result += "<br>\r\n";
  result += "<br>-->\r\n";
  result += "Teller van wiekenas omwentelingen: \r\n";
  result += "<h2><span id='revolutions'>-</span></h2>\r\n";
  result += "<br>\r\n";
  result += "Aantal enden per minuut: \r\n";
  result += "<h2><span id='viewPulsesPerMinute'>-</span></h2>\r\n";
  result += "<br>\r\n";
  result += "<div id='message'></div>\r\n";
  result += "<br>\r\n";
  result += "<a href='/help/'>Show help</a>\r\n";
  result += "<br>\r\n";
  result += "<a href='/count/'>Show counts</a>\r\n";
  result += "<script>\r\n";
  result += "if(typeof(EventSource) !== 'undefined') {\r\n";
  //result += "    document.getElementById('result').innerHTML = 'sse event is supported'\r\n";
  result += "    var source = new EventSource('/data.sse/');\r\n";
  result += "    source.onmessage = function (e) {\r\n";
  result += "        try {\r\n";
  result += "            result = JSON.parse(e.data);\r\n";
  result += "            document.getElementById('revolutions').innerHTML = result.revolutions;\r\n";
  result += "            document.getElementById('rawCounter').innerHTML = result.rawCounter;\r\n";
  result += "            document.getElementById('viewPulsesPerMinute').innerHTML = result.viewPulsesPerMinute;\r\n";
  result += "            //document.getElementById('ratio').innerHTML = result.ratio;\r\n";
  result += "        }\r\n";
  result += "        catch (err) {\r\n";
  result += "            console.log('Error: ' + err)\r\n";
  result += "        }\r\n";
  result += "    }\r\n";
  result += "} else {\r\n";
  result += "    document.getElementById('message').innerHTML = 'Your browser has no Server-Sent Event support, please refresh manually'\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n</body>\r\n</html>\r\n";

  //server.sendHeader("Content-Type", "text/html");
   server.sendHeader("Cache-Control", "no-cache");
   server.sendHeader("Connection", "keep-alive");
   server.sendHeader("Pragma", "no-cache");
   server.send(200, "text/html", result);
}

void notFound(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "File Not Found\n\n";
  result += "URI: ";
  result +=  server.uri();
  result += "\nMethod: ";
  result += ( server.method() == HTTP_GET)?"GET":"POST";
  result += "\nArguments: ";
  result +=  server.args();
  result += "\n";
  for (uint8_t i=0; i< server.args(); i++){
    result += " " +  server.argName(i) + ": " +  server.arg(i) + "\n";
  }
  result += "use /count/ for measurements\n";
  result += "use /help/ to view commands and arguments\n";
  server.send(404, "text/plain", result);
}

void help(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>molen</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Valid commands\r\n";
  result += "<br><br>\r\n";
  result += "&nbsp;&nbsp;/count/&nbsp;&nbsp;show pulses and other measurment information on screen\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/help/&nbsp;&nbsp;this screen\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/device/&nbsp;&nbsp;page where you can enter device settings/\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/wifi/&nbsp;&nbsp;page where you can choose Access Point or Station/\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/ap/&nbsp;&nbsp;goto Access Point mode, goto http://192.168.4.1/\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/network/&nbsp;&nbsp;be part of a WiFi network, goto http://molen.local/ (or via some IP address)\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/settings/&nbsp;&nbsp;alter settings with arguments\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/getSettings/&nbsp;&nbsp;view current saved settings\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/saveSettings/&nbsp;&nbsp;save current settings\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/initSettings/&nbsp;&nbsp;give settings factory values\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/eraseSettings/&nbsp;&nbsp;erase settings\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/reset/&nbsp;&nbsp;reset WiFi settings\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;/data.sse&nbsp;&nbsp;get streaming data in SSE format, refresh rate is ";
  result += String(pSettings->SSE_RETRY);
  result += " ms\r\n";
  //result += "<br>\r\n";
  //result += "  /data.json/  get data in JSON format\r\n";
  result += "<br><br>\r\n";
  result += "Valid arguments after /settings/?\r\n";
  result += "<br><br>\r\n";
  result += "&nbsp;&nbsp;ratio, used to calculate the measures to revolutions of the first axis\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;&nbsp;&nbsp;Start at the blades side. Give the number of blades, the number of gear teeth of all wheels you encounter until (inclusive) you come to the wheel where the sensor is located and divide them with a point-character\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;&nbsp;&nbsp;For wheels ont the same axis, change the point-character into a minus-character\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;&nbsp;&nbsp;Example:\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;&nbsp;&nbsp;4.72.33.80.24 means: 4 blades and 4 gears to the sensor\r\n";
  result += "<br>\r\n";
  result += "&nbsp;&nbsp;&nbsp;&nbsp;4-72.33-80.24 means: 4 blades and 1st gear on the same axis. Second and third gear also on the same axis. Fourth gear has the sensor\r\n";
  result += "<br>\r\n";
  /*
  result += "  margin, after a hit, the next measurement takes place after measuring a point further then the threshold plus margin distance (0 - 254 cm)\r\n";
  result += "<br>\r\n";
  result += "  threshold, distance to the measure point (1 - 254 cm)\n";
  result += "<br>\r\n";
  */
  result += "<br><br>\r\n";
  result += "<a href='/count/'>Show counts</a>\r\n";
  result += "\r\n</body>\r\n</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}


void showSavedSettings(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>molen</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Settings\r\n";
  result += "<br><br>\r\n";
  result += "opgeslagen tellerstand: \r\n";
  result += String(pSettings->getCounter());
  result += "\r\n";
  result += "<br>\r\n";
  result += "opgeslagen opgegeven ratio: \r\n";
  result += pSettings->getRatioArgument();
  result += "\r\n";
  result += "<br>\r\n";
  result += "opgeslagen berekende ratio: \r\n";
  result += String(pSettings->ratio);
  result += "\r\n";
  result += "<br>\r\n";
  result += "opgeslagen deviceKey: \r\n";
  result += pSettings->getDeviceKey();
  result += "\r\n";
  result += "<br>\r\n";
  result += "opgeslagen berekende pulse factor: \r\n";
  result += String(pSettings->pulseFactor);
  result += "\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<a href='/count/'>Show counts</a>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void arguments(ESP8266WebServer &server, Settings * pSettings)
{
  // Prepare the response. Start with the common header:
  //uint8_t foundArgument = 0;
  String message = "";
  for (uint8_t i=0; i< server.args(); i++){
    if (String( server.argName(i)) == "rawCounter") {
      pSettings->setCounter(server.arg(i));
    }
    if (String( server.argName(i)) == "ratio") {
      uint8_t delimiterCount = 0;
      
      if (server.argName(i).length() > pSettings->getMAX_RATIO_ARGUMENT()) {
        message += "ratio argument is too long, maximum size is: ";
        message += String(pSettings->getMAX_RATIO_ARGUMENT());
      
      }
      else {
        for (uint8 c = 0; c <  server.arg(i).length(); c++ ) {
          if ( server.arg(i)[c] == pSettings->getAXES_DELIMITER()) {
            delimiterCount += 1;
          }
        }
        if ((delimiterCount > pSettings->getMAX_AXES()) || (delimiterCount > pSettings->getMAX_WHEELS())) {
          message += "ratio argument is invalid, must be: bladeCount-gearTeeth.gearTeeth-gearTeeth ... Set value to 1";
          pSettings->setRatioArgument(pSettings->getFactoryRatioArgument());
          pSettings->ratio = 1.0;
          pSettings->pulseFactor = 1.0;
        }
        else {
          pSettings->setRatioArgument(server.arg(i));
          pSettings->calculateRatio( server.arg(i));  // where settings.ratio is set
          pSettings->calculatePulseFactor ( server.arg(i));  // where settings.pulseFactor is set
        }
        pSettings->saveSettings();
      }     
    }
  }
}

void device(ESP8266WebServer &server, Settings * pSettings)
{
  String result = "<!DOCTYPE HTML><html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>molen</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Settings for the device\r\n";
  result += "<br><br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"device\" checked>Device\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"targetServerData\">Target server data\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"settings\" onclick=\"displaySettings()\" value=\"targetServer\">Target server\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<div id=\"device\">\r\n";
  result += "    <br>\r\n";
  result += "    Set the WiFi start Mode <input id=\"startWiFiMode\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryStartModeWiFi();
  result += "\" value=\"reset\">\r\n";
  result += "    <br>\r\n";
  result += "    <input type=\"radio\" name=\"startWiFiMode\" value=\"ap\" ";
  result += (pSettings->beginAsAccessPoint() == true)?"checked":"";
  result += "> start as Access Point\r\n";
  result += "    <br>\r\n";
  result += "    <input type=\"radio\" name=\"startWiFiMode\" value=\"network\" ";
  result += (pSettings->beginAsAccessPoint() == true)?"":"checked";
  result += "> start as Network Station\r\n";
  result += "    <br><br>\r\n";
  result += "  Counter: <input type=\"text\" name=\"counter\" min=\"0\" max=\"4294967296\" maxlength=\"10\" size=\"12\" placeholder=\"";
  result += String(pSettings->getCounter());
  result += "\" title=\"This shows the current count, you may reset is to another value (0 - 4294967296)\" value=\"\" factorySetting=\"124\" onkeyup=\"checkNumber(this, 'counterMessage', 'Invalid counter (0 - 4294967296)');\">\r\n";
  result += "    <input id=\"counter\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += String(pSettings->getFactoryCounter());
  result += "\" value=\"reset\">\r\n";
  result += "    <span id=\"counterMessage\"></span><br><br>\r\n";
  result += "  <br>\r\n";
  result += "  Ratio: <input type=\"text\" name=\"ratio\" maxlength=\"64\" size=\"40\" placeholder=\"4-72.33-80.24\" title=\"4-72.33-80\" value=\"";
  result += pSettings->getRatioArgument();
  result += "\" onkeyup=\"checkRatio(this, 'ratioMessage', 'Invalid ratio character or combination (-. -- .. .-)');\">\r\n";
  result += "    <input id=\"ratio\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryRatioArgument();
  result += "\" value=\"reset\">\r\n";
  result += "  <span id=\"ratioMessage\"></span><br><br>\r\n";
  result += "  After saving, wait until about 5 to 10 seconds.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"deviceButton\" type=\"button\" name=\"deviceButton\" value=\"Save\" onclick=\"saveDevice(this)\">\r\n";
  result += "  <input type=\"button\" name=\"deviceCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"targetServerData\">\r\n";
  result += "      <br>\r\n";
  result += "      Handle data for the target server\r\n";
  result += "      <br>\r\n";
  result += "      <input type=\"checkbox\" name=\"allowSendToTarget\" onclick=\"allowSendToTargetCheck(this)\" value=\"allow\" ";
  result += (pSettings->allowSendingData() == true)?"checked":"";
  result += "> allow sending data to the target server\r\n";
  result += "      <input id=\"allowSendToTarget\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryAllowSendData();
  result += "\" value=\"reset\">\r\n";
  result += "      <br><br>\r\n";
  result += "      <div id=\"allowed\">\r\n";
  result += "        Is the building open? <input id=\"entree\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryEntree();
  result += "\" value=\"reset\">\r\n";
  result += "        <br>\r\n";
  result += "        <input type=\"radio\" name=\"entree\" value=\"open\" ";
  result += (pSettings->getIsOpen() == true)?"checked":"";
  result += "> flag as Open\r\n";
  result += "        <br>\r\n";
  result += "        <input type=\"radio\" name=\"entree\" value=\"closed\" ";
  result += (pSettings->getIsOpen() == true)?"":"checked";
  result += "> flag as Closed\r\n";
  result += "        <br><br>\r\n";
  result += "        <input type=\"checkbox\" name=\"showDataOnTarget\" onclick=\"showDataOnTargetCheck(this)\" value=\"show\" ";
  result += (pSettings->getShowData() == true)?"checked":"";
  result += "> show speed and message on the target server\r\n";
  result += "        <input id=\"showDataOnTarget\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryShowData();
  result += "\" value=\"reset\">\r\n";
  result += "        <br><br>\r\n";
  result += "        <div id=\"showMessage\">\r\n";
  result += "          Message: <input type=\"text\" name=\"message\" maxlength=\"80\" size=\"40\" placeholder=\"message\" value=\"\"> message on the target server (max 80 characters)\r\n";
  result += "          <input id=\"message\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"\" value=\"reset\">\r\n";
  result += "          <br><br>\r\n";
  result += "        </div>\r\n";
  result += "      </div>\r\n";
  result += "      <span id=\"ssidList\">Please wait for a list or a message to show here</span>\r\n";
  result += "  <br><br>\r\n";
  result += "  After saving, wait about 5 to 10 seconds.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"targetServerDataButton\" type=\"button\" name=\"targetServerDataButton\" value=\"Save\" onclick=\"saveTargetServerData(this)\">\r\n";
  result += "  <input type=\"button\" name=\"targetServerDataCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"targetServer\">\r\n";
  result += "    <br>\r\n";
  result += "    Target server\r\n";
  result += "    <br>\r\n";
  result += "  Domain name: <input type=\"text\" name=\"targetServer\" maxlength=\"32\" size=\"33\" placeholder=\"protocol://domain name\" value=\"";
  result += pSettings->getTargetServer();
  result += "\"> Max 32 characters\r\n";
  result += "    <input id=\"targetServer\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryTargetServer();
  result += "\" value=\"reset\">\r\n";
  result += "    <br>\r\n";
  result += "    Port: <input type=\"text\" name=\"targetPort\" min=\"0\" max=\"65536\" maxlength=\"5\" size=\"6\" placeholder=\"port\" title=\"0 - 65536\" value=\"";
  result += String(pSettings->getTargetPort());
  result += "\"  onkeyup=\"checkNumber(this, 'portMessage', 'Invalid counter (0 - 65536)');\">\r\n";
  result += "    <input id=\"targetPort\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += String(pSettings->getFactoryTargetPort());
  result += "\" value=\"reset\">\r\n";
  result += "    <span id=\"portMessage\"></span>\r\n";
  result += "    <br>\r\n";
  result += "    Path: <input type=\"text\" name=\"targetPath\" maxlength=\"16\" size=\"17\" placeholder=\"path\" value=\"";
  result += pSettings->getTargetPath();
  result += "\"> Max 16 characters\r\n";
  result += "    <input id=\"targetPath\" type=\"button\" onclick=\"factorySetting(this)\" reset=\"";
  result += pSettings->getFactoryTargetPath();
  result += "\" value=\"reset\">\r\n";
  result += "  <br><br>\r\n";
  result += "  After saving, wait about 5 to 10 seconds and then go to <a href=\"http://molen.local/count/\">http://molen.local/count/</a> (or a given IP address) to connect.\r\n";
  result += "    <br>\r\n";
  result += "  <input id=\"targetServerButton\" type=\"button\" name=\"targetServerButton\" value=\"Save\" onclick=\"saveTargetServer(this)\">\r\n";
  result += "  <input type=\"button\" name=\"targetServerCancelButton\" value=\"Cancel\" onclick=\"cancelSettings()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "  function factorySetting(component) {\r\n";
  result += "      var id = component.id || \"\";\r\n";
  result += "      var factoryValue = component.getAttribute(\"reset\");\r\n";
  result += "      var names = document.getElementsByName(id) || [];\r\n";
  result += "      if (names.length > 0) {\r\n";
  result += "        var type = names[0].getAttribute(\"type\");\r\n";
  result += "        if (type == \"radio\")\r\n";
  result += "        {\r\n";
  result += "            for (var i = 0; i < names.length; i++)\r\n";
  result += "            {\r\n";
  result += "                if (names[i].value == factoryValue) {\r\n";
  result += "                    names[i].checked = true;\r\n";
  result += "                };\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        if (type == \"checkbox\")\r\n";
  result += "        {\r\n";
  result += "            var factoryValueArray = factoryValue.split(\",\");\r\n";
  result += "            for (var i = 0; i < names.length; i++)\r\n";
  result += "            {\r\n";
  result += "                names[i].checked = false;\r\n";
  result += "                for (var e = 0; e < factoryValueArray.length; e++)\r\n";
  result += "                {\r\n";
  result += "                    if (names[i].value == factoryValueArray[e].trim()) {\r\n";
  result += "                        names[i].checked = true;\r\n";
  result += "                    }\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        if (type == \"text\")\r\n";
  result += "        {\r\n";
  result += "            names[0].value = factoryValue;\r\n";
  result += "        }\r\n";
  result += "      }\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function checkRatio(component, messageId, message) {\r\n";
  result += "    var buttonId = component.parentNode.id + \"Button\";\r\n";
  result += "    var validCharacterString = \"0123456789-.\";\r\n";
  result += "    var valid = false;\r\n";
  result += "      var currentChar = component.value.charAt(component.value.length - 1);\r\n";
  result += "      if (validCharacterString.indexOf(currentChar) > -1) {\r\n";
  result += "    valid = true;\r\n";
  result += "    };\r\n";
  result += "      if ( (component.value.indexOf(\".-\") > -1) ||\r\n";
  result += "           (component.value.indexOf(\"--\") > -1) ||\r\n";
  result += "           (component.value.indexOf(\"..\") > -1) ||\r\n";
  result += "           (component.value.indexOf(\"-.\") > -1) ) {\r\n";
  result += "          valid = false;\r\n";
  result += "      }\r\n";
  result += "    if (valid) {\r\n";
  result += "      document.getElementById(messageId).innerHTML = \"\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "    document.getElementById(messageId).innerHTML = message;\r\n";
  result += "    }\r\n";
  result += "    document.getElementById(buttonId).disabled = !valid;\r\n";
  result += "    return valid;\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function checkNumber(component, messageId, message) {\r\n";
  result += "    var buttonId = component.parentNode.id + \"Button\";\r\n";
  result += "  //var validCharacterString = \"0123456789-.\";\r\n";
  result += "  var valid = false;\r\n";
  result += "    if ((component.value >= Number(component.getAttribute(\"min\"))) && (component.value <= Number(component.getAttribute(\"max\")))) {\r\n";
  result += "        valid = true;\r\n";
  result += "    }\r\n";
  result += "    if (valid) {\r\n";
  result += "      document.getElementById(messageId).innerHTML = \"\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "    document.getElementById(messageId).innerHTML = message;\r\n";
  result += "    }\r\n";
  result += "    document.getElementById(buttonId).disabled = !valid;\r\n";
  result += "    return valid;\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function cancelSettings() {\r\n";
  result += "  window.location.reload();\r\n";
  result += "  }\r\n";
  result += "  function sendData(data) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", \"/deviceSettings/\");\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "      xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "        var myResponseText = \"\";\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "          myResponseText = this.responseText || \"\";\r\n";
  result += "        }\r\n";
  result += "        if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "          myResponseText = this.statusText || \"\";\r\n";
  result += "        }\r\n";
  result += "        document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "      }\r\n";
  //result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveDevice(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var startWiFiMode = \"\";\r\n";
  result += "        var counter = \"\";\r\n";
  result += "        var ratio = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"startWiFiMode\") {\r\n";
  result += "                if (children[i].checked == true) {\r\n";
  result += "                    startWiFiMode = children[i].value || true;\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"counter\") {\r\n";
  result += "                counter = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"ratio\") {\r\n";
  result += "                ratio = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=device\" + \"&startWiFiMode=\" + startWiFiMode + \"&counter=\" + counter + \"&ratio=\" + ratio;\r\n";
  result += "        sendData(params);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveTargetServerData(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var allowSendingData = \"\";\r\n";
  result += "        var isOpen = \"\";\r\n";
  result += "        var showData = \"\";\r\n";
  result += "        var message = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"allowSendToTarget\") {\r\n";
  result += "                allowSendingData = children[i].checked == true;\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        children = document.getElementById(\"allowed\").childNodes;\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"entree\") {\r\n";
  result += "                if (children[i].checked == true) {\r\n";
  result += "                    isOpen = children[i].value || \"\";\r\n";
  result += "                }\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"showDataOnTarget\") {\r\n";
  result += "                showData = children[i].checked == true;\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        children = document.getElementById(\"showMessage\").childNodes;\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"message\") {\r\n";
  result += "                message = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=targetServerData\" + \"&allowSendingData=\" + allowSendingData + \"&isOpen=\" + isOpen + \"&showData=\" + showData + \"&message=\" + encodeURIComponent(message);\r\n";
  result += "        sendData(params);\r\n";
  result += "    }\r\n";
  result += "\r\n";
  result += "  function saveTargetServer(content) {\r\n";
  result += "        var children = content.parentNode.childNodes;\r\n";
  result += "        var targetServer = \"\";\r\n";
  result += "        var targetPort = \"\";\r\n";
  result += "        var ratio = \"\";\r\n";
  result += "        for (var i = 0; i < children.length; i++) {\r\n";
  result += "            if (children[i].name == \"targetServer\") {\r\n";
  result += "                targetServer = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"targetPort\") {\r\n";
  result += "                targetPort = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "            if (children[i].name == \"targetPath\") {\r\n";
  result += "                targetPath = children[i].value || \"\";\r\n";
  result += "            }\r\n";
  result += "        }\r\n";
  result += "        var params = \"name=targetServer\" + \"&targetServer=\" + encodeURIComponent(targetServer) + \"&targetPort=\" + targetPort + \"&targetPath=\" + encodeURIComponent(targetPath);\r\n";
  result += "        sendData(params);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function loadWiFiNetworkList() {\r\n";
  result += "  var xhttp = new XMLHttpRequest();\r\n";
  result += "  xhttp.onreadystatechange = function() {\r\n";
  result += "    if (this.readyState == 4 && this.status == 200) {\r\n";
  result += "      document.getElementById(\"ssidList\").innerHTML = this.responseText;\r\n";
  result += "    }\r\n";
  result += "  };\r\n";
  result += "  xhttp.open(\"GET\", \"/networkssid/\", true);\r\n";
  result += "  xhttp.send();\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function allowSendToTargetCheck(content) {\r\n";
  result += "    if (content.checked == true) {\r\n";
  result += "        document.getElementById(\"allowed\").style.display=\"block\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "        document.getElementById(\"allowed\").style.display=\"none\";\r\n";
  result += "    };\r\n";
  result += "}\r\n";
  result += "\r\n";
  result += "function showDataOnTargetCheck(content) {\r\n";
  result += "    if (content.checked == true) {\r\n";
  result += "        document.getElementById(\"showMessage\").style.display=\"block\";\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "        document.getElementById(\"showMessage\").style.display=\"none\";\r\n";
  result += "    };\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function displaySettings() {\r\n";
  result += "var ele = document.getElementsByName('settings');\r\n";
  result += "\r\n";
  result += "  for(i = 0; i < ele.length; i++) {\r\n";
  result += "    if(ele[i].checked) {\r\n";
  result += "      document.getElementById(ele[i].value).style.display=\"block\";\r\n";
  result += "//      if (ele[i].value == 'network') {\r\n";
  result += "//        loadWiFiNetworkList();\r\n";
  result += "//      }\r\n";
  result += "    }\r\n";
  result += "    else {\r\n";
  result += "      document.getElementById(ele[i].value).style.display=\"none\";\r\n";
  result += "    }\r\n";
  result += "  }\r\n";
  result += "}\r\n";
  result += "displaySettings();\r\n";
  result += "</script>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void wifi(ESP8266WebServer &server, Settings * pSettings, WiFiSettings * pWiFiSettings)
{
  String result = "<!DOCTYPE HTML>\r\n<html>\r\n";
  result += "<head>\r\n";
  result += "<meta charset=\"utf-8\">\r\n";
  result += "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n";
  result += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n";
  result += "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n";
  result += "<link rel='icon' type='image/png' href='data:image/png;base64,iVBORw0KGgo='>\r\n";
  result += "<title>molen</title>\r\n";
  result += "</head>\r\n";
  result += "<body>\r\n";
  result += "Don't want to share with internet or no WiFi available? Choose AccessPoint\r\n";
  result += "<br>\r\n";
  result += "You want to share with internet and have WiFi available? Choose Network\r\n";
  result += "<br><br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"ap\">Access Point\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"network\">Network Station\r\n";
  result += "<br>\r\n";
  result += "<input type=\"radio\" name=\"wifi\" onclick=\"displayWiFiMode()\" value=\"erase\">Go to Erase-WiFi-Data menu\r\n";
  result += "<br>\r\n";
  result += "<br>\r\n";
  result += "<div id=\"ap\">\r\n";
  result += "  Clients can get access to this Access Point using the SSID and password entered below\r\n";
  result += "  <br>\r\n";
  result += "  An empty SSID will result in a default SSID for the device\r\n";
  result += "  <br>\r\n";
  result += "  An empty password will result in an unencrypted, open Access Point\r\n";
  result += "  <br>\r\n";
  result += "  SSID: <input type=\"text\" name=\"ssid\" maxlength=\"32\" size=\"33\" placeholder=\"";
  if (pWiFiSettings->getAccessPointSSID() == "")
  {
    result += "SSID";
  }
  else
  {
    result += pWiFiSettings->getAccessPointSSID();
  }
  result += "\" value=\"";
  result += pWiFiSettings->getAccessPointSSID();
  result += "\">\r\n";
  result += "  <br>\r\n";
  result += "  Password: <input type=\"password\" name=\"password\" maxlength=\"32\" size=\"33\" placeholder=\"";
  if (pWiFiSettings->getAccessPointPassword() == "")
  {
    result += "password";
  }
  else
  {
    result += pWiFiSettings->getAccessPointPassword();
  }
  result += "\" value=\"";
  result += pWiFiSettings->getAccessPointPassword();
  result += "\" onkeyup=\"checkURIComponent(this, 'apPasswordMessage', 'Invalid password character');\">\r\n";
  result += " <span id=\"apPasswordMessage\"></span>\r\n";
  result += "  <br><br>\r\n";
  result += "  After saving, wait about 5 to 10 seconds and then go to <a href=\"http://192.168.4.1/count/\">http://192.168.4.1/count/</a> to connect.\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"apButton\" type=\"button\" name=\"apButton\" value=\"Save\" onclick=\"saveAP(this)\">\r\n";
  result += "  <input type=\"button\" name=\"apCancelButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "<div id=\"network\">\r\n";
  result += "  Connect to one of the WiFi networks below\r\n";
  result += "  <br><br>\r\n";
  result += "  <span id=\"ssidList\">Please wait for a list or a message to show here</span>\r\n";
  result += "  <br><br>\r\n";
  result += "  <span id=\"selectedWiFiPassword\">";
  result += "Give the password for the selected WiFi network <span id=\"selectedWiFi\"></span>\r\n";
  result += "     <br>\r\n";
  result += "     Password: <input type=\"password\" name=\"password\" maxlength=\"32\" size=\"33\" placeholder=\"password\" value=\"";
  result += "\" onkeyup=\"checkURIComponent(this, 'networkPasswordMessage', 'Invalid password character');\">\r\n";
  result += "     <br><br>\r\n";
  result += "  </span>\r\n";
  result += "After saving, wait about 5 to 10 seconds and then go to <a href=\"http://molen.local/count/\">http://molen.local/count/</a> (or a given IP address) to connect.\r\n";
  result += "  <br>\r\n";
  result += "   <input id=\"networkButton\" type=\"button\" name=\"networkButton\" value=\"Save\" onclick=\"saveNetwork(this)\">\r\n";
  result += "   <input type=\"button\" name=\"networkCancelButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "  <span id=\"networkPasswordMessage\"></span>\r\n";
  result += "</div>\r\n";
  result += "<div id=\"erase\">\r\n";
  result += "  !!!Warning!!!\r\n";
  result += "  <br><br>\r\n";
  result += "  A click on an Erase button will immediately erase saved data! Your current connection will stay alive.\r\n";
  result += "  <br><br>\r\n";
  result += "Do NOT Erase and <input type=\"button\" name=\"networkButton\" value=\"Cancel\" onclick=\"cancelWiFi()\">\r\n";
  result += "  <br><br>\r\n";
  result += "  <input id=\"eraseAPData\" type=\"button\" name=\"eraseAPDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Erase Access Point data, will result in an unencrypted, open Access Point\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"eraseNetworkData\" type=\"button\" name=\"eraseNetworkDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Erase Network data\r\n";
  result += "  <br>\r\n";
  result += "  <input id=\"eraseWiFiData\" type=\"button\" name=\"eraseWiFiDataButton\" value=\"Erase\" onclick=\"eraseWiFiData(this)\"> Erase Access Point AND Network data\r\n";
  result += "</div>\r\n";
  result += "\r\n";
  result += "  <br>\r\n";
  result += "<div id=\"sendMessage\"></div>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function checkURIComponent(component, messageId, message) {\r\n";
  result += "  var invalidCharacterArray = [\"&\"]\r\n";
  result += "  var buttonNodeId = component.parentNode.id;\r\n";
  result += "  if (buttonNodeId == \"selectedWiFiPassword\") {\r\n";
  result += "    buttonNodeId = component.parentNode.parentNode.id;\r\n";
  result += "  };\r\n";
  result += "  var buttonId = buttonNodeId + \"Button\"\r\n";
  result += "   var valid = true;\r\n";
  result += "   for (var c = 0; c < invalidCharacterArray.length; c++) {\r\n";
  result += "    if (component.value.indexOf(invalidCharacterArray[c]) > -1) {\r\n";
  result += "      valid = false;\r\n";
  result += "      break;\r\n";
  result += "    };\r\n";
  result += "  };\r\n";
  result += "  if (valid) {\r\n";
  result += "    document.getElementById(messageId).innerHTML = \"\";\r\n";
  result += "  }\r\n";
  result += "  else {\r\n";
  result += "    document.getElementById(messageId).innerHTML = message;\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(buttonId).disabled = !valid;\r\n";
  result += "   return valid;\r\n";
  result += "}\r\n";
  result += "  function cancelWiFi() {\r\n";
  result += "    window.location.reload();\r\n";
  result += "  }\r\n";
  result += "  function sendData(data) {\r\n";
  result += "    var xhr = new XMLHttpRequest();   // new HttpRequest instance\r\n";
  result += "    xhr.open(\"POST\", \"/wifiConnect/\");\r\n";
  result += "    xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n";
  result += "    //xhr.setRequestHeader(\"Content-Type\", \"application/json\");\r\n";
  result += "   document.getElementById(\"sendMessage\").innerHTML = \"Please wait\";\r\n";
  result += "    xhr.onreadystatechange = function() { // Call a function when the state changes.\r\n";
  result += "     var myResponseText = \"\";\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status === 200) {\r\n";
  result += "       myResponseText = this.responseText || \"\";\r\n";
  result += "     }\r\n";
  result += "      if (this.readyState === XMLHttpRequest.DONE && this.status !== 200) {\r\n";
  result += "       myResponseText = this.statusText || \"\";\r\n";
  result += "      }\r\n";
  result += "      document.getElementById(\"sendMessage\").innerHTML = myResponseText;\r\n";
  result += "    }\r\n";
  result += "    xhr.send(data);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveAP(content) {\r\n";
  result += "    var children = content.parentNode.childNodes;\r\n";
  result += "    var ssid = \"\";\r\n";
  result += "    var password = \"\";\r\n";
  result += "    for (var i = 0; i < children.length; i++) {\r\n";
  result += "      if (children[i].name == \"ssid\") {\r\n";
  result += "        ssid = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "      if (children[i].name == \"password\") {\r\n";
  result += "        password = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "    }\r\n";
  result += "    var params = \"name=ap\" + \"&ssid=\" + ssid + \"&password=\" + password;\r\n";
  result += "    sendData(params);\r\n";
  result += "    //var json_upload = JSON.stringify({name:\"ap\", ssid:ssid, password:password});\r\n";
  result += "    //sendData(json_upload);\r\n";
  result += "  }\r\n";
  result += "\r\n";
  result += "  function saveNetwork(content) {\r\n";
  result += "    var children = document.getElementById(\"selectedWiFiPassword\").childNodes;\r\n";
  result += "    var ssid = document.getElementById(\"selectedWiFi\").innerHTML;\r\n";
  result += "    var password = \"\";\r\n";
  result += "    for (var i = 0; i < children.length; i++) {\r\n";
  result += "      if (children[i].name == \"password\") {\r\n";
  result += "        password = children[i].value || \"\";\r\n";
  result += "      }\r\n";
  result += "    }\r\n";
  result += "    var params = \"name=network\" + \"&ssid=\" + ssid + \"&password=\" + password;\r\n";
  result += "    sendData(params);\r\n";
  result += "    //var json_upload = JSON.stringify({name:\"network\", ssid:ssid, password:password});\r\n";
  result += "    //sendData(json_upload);\r\n";
  result += "  }\r\n";
  result += "  function eraseWiFiData(content) {\r\n";
  result += "  var params = \"name=erase\" + \"&target=\" + content.id;\r\n";
  result += "      sendData(params);\r\n";
  result += "  }\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";

  result += "function showNetworkList(networks) {\r\n";
  result += "  var showNetworkList = [];\r\n";
  result += "  var showNetwork = \"\";\r\n";
  result += "  var networkList = (new Function(\"return [\" + networks + \"];\")());\r\n";
  result += "  networkList.sort((a,b) => (a.dBm > b.dBm) ? 1: (a.dBm === b.dBm) ? ((a.ssid > b.ssid) ? 1: -1) : -1);\r\n";
  result += "  networkList = networkList.filter(function(e) { return e.dBm > -80});\r\n";
  result += "  sortedList = [...networkList].reverse();\r\n";
  result += "  for (var key in sortedList) {\r\n";
  result += "    var value = sortedList[key]\r\n";
  result += "    showNetworkList.push(Object.values(value)[0]);\r\n";
  result += "  }\r\n";
  result += "  var uniqueShowNetworkList = [...new Set(showNetworkList)];\r\n";
  result += "  for (var key in uniqueShowNetworkList) {\r\n";
  result += "    showNetwork += \"<div>\" + uniqueShowNetworkList[key] + \"</div>\";\r\n";
  result += "  }\r\n";
  result += "  if (showNetwork == \"\") {\r\n";
  result += "    showNetwork = \"No WiFi signal available\"\r\n";
  result += "  }\r\n";
  result += "  else {\r\n";
  result += "    document.getElementById(\"selectedWiFiPassword\").style.display=\"block\"\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(\"ssidList\").innerHTML = showNetwork;\r\n";
  result += "}\r\n"; 
  result += "function selectNetworkSSID(content) {\r\n";
  result += "  ssid = \"\"\r\n";
  result += "  if (content.name == \"networkSSID\") {\r\n";
  result += "    ssid = content.value;\r\n";
  result += "  }\r\n";
  result += "  document.getElementById(\"selectedWiFi\").innerHTML = ssid;\r\n";
  result += "}\r\n";
  result += "function loadWiFiNetworkList() {\r\n";
  result += "  var xhttp = new XMLHttpRequest();\r\n";
  result += "  xhttp.onreadystatechange = function() {\r\n";
  result += "    if (this.readyState == 4 && this.status == 200) {\r\n";
  result += "      showNetworkList(this.responseText);\r\n";
  result += "    }\r\n";
  result += "  };\r\n";
  result += "  xhttp.open(\"GET\", \"/networkssid/\", true);\r\n";
  result += "  xhttp.send();\r\n";
  result += "}\r\n";
  result += "</script>\r\n";
  result += "\r\n";
  result += "<script>\r\n";
  result += "function displayWiFiMode() {\r\n";
  result += "var ele = document.getElementsByName('wifi');\r\n";
  result += "\r\n";
  result += "  for(i = 0; i < ele.length; i++) {\r\n";
  result += "    if(ele[i].checked) {\r\n";
  result += "       document.getElementById(ele[i].value).style.display=\"block\";\r\n";
  result += "       if (ele[i].value == 'network') {\r\n";
  result += "        document.getElementById(\"selectedWiFi\").innerHTML = \"\"\r\n";
  result += "        document.getElementById(\"selectedWiFiPassword\").style.display=\"none\"\r\n";
  result += "         loadWiFiNetworkList();\r\n";
  result += "       }\r\n";
  result += "     }\r\n";
  result += "     else {\r\n";
  result += "       document.getElementById(ele[i].value).style.display=\"none\";\r\n";
  result += "     }\r\n";
  result += "  }\r\n";
  result += "}\r\n";
  result += "displayWiFiMode();\r\n";
  result += "</script>\r\n";
  result += "</body>\r\n";
  result += "</html>\r\n";
  
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/html", result);
}

void sse(ESP8266WebServer &server, Settings * pSettings, uint32_t revolutions, uint32_t viewPulsesPerMinute)
{
  String result = "retry: ";
  result += String(pSettings->SSE_RETRY);
  result += "\r\n";
  result += "data: ";
  result += "{";
  result += "\"ratio\":";
  result += String(pSettings->ratio);
  result += ",";
  result += "\"revolutions\":";
  result += String(revolutions);
  result += ",";
  result += "\"rawCounter\":";
  result += String(pSettings->getCounter());
  result += ",";
  result += "\"viewPulsesPerMinute\":";
  result += String(viewPulsesPerMinute);
  result += "}\r\n\r\n";
  server.sendHeader("Cache-Control", "no-cache");
  server.sendHeader("Connection", "keep-alive");
  server.sendHeader("Pragma", "no-cache");
  server.send(200, "text/event-stream", result);

}